; This Source Code Form is subject to the terms of the Mozilla Public
; License, v. 2.0. If a copy of the MPL was not distributed with this
; file, You can obtain one at https://mozilla.org/MPL/2.0/.

(ns noahtheduke.splint.replace-test
  (:require
    [expectations.clojure.test :refer [defexpect expect]]
    [noahtheduke.splint.replace :as sut]))

(defexpect revert-splint-reader-macros-test
  (expect '(clojure.core/deref ?a)
    (sut/revert-splint-reader-macros '(splint/deref ?a)))
  (expect '(clojure.core/deref (?a))
    (sut/revert-splint-reader-macros '(splint/deref (?a))))
  (expect '(clojure.core/fn [arg] (+ ?a arg))
    (sut/revert-splint-reader-macros '(splint/fn [arg] (+ ?a arg))))
  (expect (list (symbol "#=") '(+ 1 2))
    (sut/revert-splint-reader-macros '(splint/read-eval (+ 1 2))))
  (expect '(clojure.core/re-pattern ?a)
    (sut/revert-splint-reader-macros '(splint/re-pattern ?a)))
  (expect #(instance? java.util.regex.Pattern %)
    (sut/revert-splint-reader-macros '(splint/re-pattern "a")))
  (expect #"a"
    (str (sut/revert-splint-reader-macros '(splint/re-pattern "a"))))
  (expect '(var ?a)
    (sut/revert-splint-reader-macros '(splint/var ?a)))
  (expect '(var (?a c))
    (sut/revert-splint-reader-macros '(splint/var (?a c))))
  (expect (symbol "`?a")
    (sut/revert-splint-reader-macros '(splint/syntax-quote ?a)))
  (expect (list (symbol "`") '(+ ?a (clojure.core/unquote b) c#))
    (sut/revert-splint-reader-macros '(splint/syntax-quote (+ ?a ~b c#))))
  (expect '(clojure.core/unquote ?a)
    (sut/revert-splint-reader-macros '(splint/unquote ?a)))
  (expect '(clojure.core/unquote (?a))
    (sut/revert-splint-reader-macros '(splint/unquote (?a))))
  (expect '(clojure.core/unquote-splicing ?a)
    (sut/revert-splint-reader-macros '(splint/unquote-splicing ?a)))
  (expect '(clojure.core/unquote-splicing (?a))
    (sut/revert-splint-reader-macros '(splint/unquote-splicing (?a)))))

(defexpect postwalk-splicing-replace-test
  (expect '(splint/deref b)
    (sut/postwalk-splicing-replace {'?a 'b} '(splint/deref ?a)))
  (expect '(splint/deref (b))
    (sut/postwalk-splicing-replace {'?a 'b} '(splint/deref (?a))))
  (expect '(splint/fn [arg] (+ b arg))
    (sut/postwalk-splicing-replace {'?a 'b} '(splint/fn [arg] (+ ?a arg))))
  (expect '(splint/read-eval (+ b 2))
    (sut/postwalk-splicing-replace {'?a 'b} '(splint/read-eval (+ ?a 2))))
  (expect '(splint/re-pattern "asdfd")
    (sut/postwalk-splicing-replace {'?a "asdfd"} '(splint/re-pattern ?a)))
  (expect '(splint/var b)
    (sut/postwalk-splicing-replace {'?a 'b} '(splint/var ?a)))
  (expect '(splint/var (b c))
    (sut/postwalk-splicing-replace {'?a 'b} '(splint/var (?a c))))
  (expect '(splint/syntax-quote b)
    (sut/postwalk-splicing-replace {'?a 'b} '(splint/syntax-quote ?a)))
  (expect '(splint/syntax-quote (+ b ~b c#))
    (sut/postwalk-splicing-replace {'?a 'b} '(splint/syntax-quote (+ ?a ~b c#))))
  (expect '(splint/unquote b)
    (sut/postwalk-splicing-replace {'?a 'b} '(splint/unquote ?a)))
  (expect '(splint/unquote (b))
    (sut/postwalk-splicing-replace {'?a 'b} '(splint/unquote (?a))))
  (expect '(splint/unquote-splicing b)
    (sut/postwalk-splicing-replace {'?a 'b} '(splint/unquote-splicing ?a)))
  (expect '(splint/unquote-splicing (b))
    (sut/postwalk-splicing-replace {'?a 'b} '(splint/unquote-splicing (?a)))))
