; This Source Code Form is subject to the terms of the Mozilla Public
; License, v. 2.0. If a copy of the MPL was not distributed with this
; file, You can obtain one at https://mozilla.org/MPL/2.0/.

(ns noahtheduke.splint.vendor)

(set! *warn-on-reflection* true)

(def default-imports
  '#{Boolean
     Byte
     Character
     Class
     ClassLoader
     Compiler
     Double
     Enum
     Float
     InheritableThreadLocal
     Integer
     Long
     Math
     Number
     Object
     Package
     Process
     ProcessBuilder
     Runtime
     RuntimePermission
     SecurityManager
     Short
     StackTraceElement
     StrictMath
     String
     StringBuffer
     StringBuilder
     System
     Thread
     ThreadGroup
     ThreadLocal
     Throwable
     Void
     Appendable
     CharSequence
     Cloneable
     Comparable
     Iterable
     Readable
     Runnable
     Callable
     BigInteger
     BigDecimal
     ArithmeticException
     ArrayIndexOutOfBoundsException
     ArrayStoreException
     ClassCastException
     ClassNotFoundException
     CloneNotSupportedException
     EnumConstantNotPresentException
     Exception
     IllegalAccessException
     IllegalArgumentException
     IllegalMonitorStateException
     IllegalStateException
     IllegalThreadStateException
     IndexOutOfBoundsException
     InstantiationException
     InterruptedException
     NegativeArraySizeException
     NoSuchFieldException
     NoSuchMethodException
     NullPointerException
     NumberFormatException
     RuntimeException
     SecurityException
     StringIndexOutOfBoundsException
     TypeNotPresentException
     UnsupportedOperationException
     AbstractMethodError
     AssertionError
     ClassCircularityError
     ClassFormatError
     Error
     ExceptionInInitializerError
     IllegalAccessError
     IncompatibleClassChangeError
     InstantiationError
     InternalError
     LinkageError
     NoClassDefFoundError
     NoSuchFieldError
     NoSuchMethodError
     OutOfMemoryError
     StackOverflowError
     ThreadDeath
     UnknownError
     UnsatisfiedLinkError
     UnsupportedClassVersionError
     VerifyError
     VirtualMachineError
     Thread$UncaughtExceptionHandler
     Thread$State
     Deprecated
     Override
     SuppressWarnings})
