name: CI

on: [push]

jobs:
  lint:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        java: [11, 17, 21]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Setup clojure-lsp
        uses: clojure-lsp/setup-clojure-lsp@v1
        with:
          clojure-lsp-version: 2025.03.07-17.42.36

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          cli: 1.12.0.1479
          bb: 1.12.205

      - name: Cache clojure dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: cljdeps-${{ hashFiles('deps.edn', 'bb.edn') }}
          restore-keys: cljdeps-

      - name: clojure-lsp
        run: clojure-lsp diagnostics

      - name: splint self
        run: bb run splint

      - name: Tests
        run: |
          clojure -M:v1.10:dev:test:runner --output dots
          clojure -M:v1.11:dev:test:runner --output dots
          clojure -M:v1.12:dev:test:runner --output dots
